-- Create a table for public profiles because auth.users is secure
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for Watchlist
create table watchlists (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  movie_id integer not null,
  media_type text not null, -- 'movie' or 'tv'
  title text not null,
  poster_path text,
  vote_average numeric,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(user_id, movie_id, media_type)
);

alter table watchlists enable row level security;

create policy "Users can view their own watchlist."
  on watchlists for select
  using ( auth.uid() = user_id );

create policy "Users can insert into their own watchlist."
  on watchlists for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete from their own watchlist."
  on watchlists for delete
  using ( auth.uid() = user_id );

-- Create a table for Watched History
create table history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  movie_id integer not null,
  media_type text not null,
  title text not null,
  poster_path text,
  vote_average numeric,
  watched_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(user_id, movie_id, media_type)
);

alter table history enable row level security;

create policy "Users can view their own history."
  on history for select
  using ( auth.uid() = user_id );

create policy "Users can insert into their own history."
  on history for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete from their own history."
  on history for delete
  using ( auth.uid() = user_id );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
