-- New-episode alerts for TV shows in a user's watchlist.
--
-- episode_notifications: one row per (user, show, season, episode) that has
-- already been pushed, so the daily `send-episode-alerts` job never alerts the
-- same episode twice. Only the service-role edge function writes here (it
-- bypasses RLS); users may read their own rows.

create table public.episode_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tv_id integer not null,
  season_number integer not null,
  episode_number integer not null,
  notified_at timestamptz not null default now(),
  unique (user_id, tv_id, season_number, episode_number)
);

create index episode_notifications_user_id_idx on public.episode_notifications (user_id);

alter table public.episode_notifications enable row level security;

create policy "Users can view their own episode notifications."
  on public.episode_notifications for select
  using (auth.uid() = user_id);
