create table public.watched_episodes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tv_id integer not null,
  season_number integer not null,
  episode_number integer not null,
  watched_at timestamptz not null default now(),
  unique (user_id, tv_id, season_number, episode_number)
);

alter table public.watched_episodes enable row level security;

create policy "Users can view their own watched episodes."
  on public.watched_episodes for select
  using (auth.uid() = user_id);

create policy "Users can insert their own watched episodes."
  on public.watched_episodes for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own watched episodes."
  on public.watched_episodes for delete
  using (auth.uid() = user_id);
