-- Release reminders ("Notify Me" on upcoming titles).
create table public.reminders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  movie_id integer not null,
  media_type text not null,
  title text not null,
  poster_path text,
  release_date date,
  created_at timestamptz not null default now(),
  unique (user_id, movie_id, media_type)
);

alter table public.reminders enable row level security;

create policy "Users can view their own reminders."
  on public.reminders for select
  using (auth.uid() = user_id);

create policy "Users can insert their own reminders."
  on public.reminders for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own reminders."
  on public.reminders for delete
  using (auth.uid() = user_id);
