-- Web Push notifications for release reminders.
--
-- push_subscriptions: one row per browser/device Push subscription, owned by a
-- user. The edge function reads these (service role) to deliver notifications.
-- reminders.notified_at: set once a release alert has been sent so the daily job
-- never notifies the same reminder twice.

create table public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now()
);

create index push_subscriptions_user_id_idx on public.push_subscriptions (user_id);

alter table public.push_subscriptions enable row level security;

create policy "Users can view their own push subscriptions."
  on public.push_subscriptions for select
  using (auth.uid() = user_id);

create policy "Users can insert their own push subscriptions."
  on public.push_subscriptions for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own push subscriptions."
  on public.push_subscriptions for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own push subscriptions."
  on public.push_subscriptions for delete
  using (auth.uid() = user_id);

alter table public.reminders add column notified_at timestamptz;
