-- Per-user daily usage counter for the CineBot AI Edge Function (rate limiting).
-- The Edge Function reads/writes this with the caller's JWT; RLS keeps each user
-- scoped to their own rows. Optional: CineBot's local recommender works without it.
create table public.cinebot_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  used_on date not null default (now() at time zone 'utc')::date,
  count integer not null default 0,
  unique (user_id, used_on)
);

alter table public.cinebot_usage enable row level security;

create policy "Users can view their own AI usage."
  on public.cinebot_usage for select
  using (auth.uid() = user_id);

create policy "Users can insert their own AI usage."
  on public.cinebot_usage for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own AI usage."
  on public.cinebot_usage for update
  using (auth.uid() = user_id);
